### ISSUE TITLE
RTK1_Core プラグインのフィードバックです。

### ISSUE THREAD

**Issue by kurotsushirou** [yamachan/jgss-hack#1]
こんにちは。プラグイン使用させていただいております。
さて、本題ですがゲームセーブファイルのない状態で、生成したツクールＭＶ日本語版にRTK1_Core.jsとRTK1_Option_EnJa.jsを導入すると、ゲーム開始後にエラーを返すようになりました。
おそらくツクールＭＶエディター側のCore.jsの更新による現象だと思われます。
ツクールＭＶのエディターのバージョンは1.６.１です。

既存のゲーム進行状況を記録したものに上記のプラグインを導入しても不具合はないのですが、新規でゲームを始める場合に、日本語英語のランゲージ選択を済ませると、

UnknowError
Error:EACCES:permission denied,mkdir'/save/'

というエラーが返ってきます。

たまたま、海外のプレイヤー向けに遊びやすいよう同プラグインを導入してみましたが、反応がいまいちだったようです。

できれば、改善をお願いしたいのですがいかがでしょうか。

どうやら、プロジェクトが古いだけのようでした。プロジェクトデータを更新したら治りました。お騒がせしました。

**Comment by yamachan** [comment]
先週からバタバタしており、メール未読が多くて Issue に気がつくのが遅れました、すみません。
また解決されたようで良かったです。

RPGツクールMV のバージョンも 1.62 に上がったようで、こちらでも動作確認をしてみますね。

ご連絡をありがとうございました！
